// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqs2OLQwJk2n0mfSfq4NzWjU49dSdyec',
    appId: '1:490250756654:web:56f238da26d66784b735bf',
    messagingSenderId: '490250756654',
    projectId: 'shoptraly-3033f',
    authDomain: 'shoptraly-3033f.firebaseapp.com',
    storageBucket: 'shoptraly-3033f.appspot.com',
    measurementId: 'G-0PL7RH36M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAy--Yakl7htZelNqR6msQPYdCHfqmNeg',
    appId: '1:490250756654:android:f68a440c0f5cdb82b735bf',
    messagingSenderId: '490250756654',
    projectId: 'shoptraly-3033f',
    storageBucket: 'shoptraly-3033f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvr533ofnyrnY1G5vXfv02VGjSbXdafmM',
    appId: '1:490250756654:ios:04440ff7649b9b29b735bf',
    messagingSenderId: '490250756654',
    projectId: 'shoptraly-3033f',
    storageBucket: 'shoptraly-3033f.appspot.com',
    iosClientId: '490250756654-1eltmefe49glih5te7be7f54idjher69.apps.googleusercontent.com',
    iosBundleId: 'com.metoly.shoptraly.shoptral1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvr533ofnyrnY1G5vXfv02VGjSbXdafmM',
    appId: '1:490250756654:ios:feef4052a21bf548b735bf',
    messagingSenderId: '490250756654',
    projectId: 'shoptraly-3033f',
    storageBucket: 'shoptraly-3033f.appspot.com',
    iosClientId: '490250756654-rkht6lap4v82e41gpfl3gm0u6qo55q43.apps.googleusercontent.com',
    iosBundleId: 'com.metoly.shoptraly.shoptral1.RunnerTests',
  );
}
